### PR TITLE
happy belated 2018

### PR DESCRIPTION
**Pull request by DoNotSpamPls**

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
bump

**Comment by Proximyst** [comment]
yo what why

**Comment by DoNotSpamPls** [comment]
@Proximyst nobody merged this shit it's almost 2019 i give up

**Comment by Proximyst** [comment]
we're not even 30% into 2018 yet

**Comment by deansheather** [comment]
merge at 100% into 2018

**Pull request closed without merging**
